// <auto-generated />
namespace Tennis.NET.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nullableintsdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nullableintsdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201610311317387_Nullable ints, date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
